Add functions to make forcefield-utilities functional as a backend loader
mosdef-hub/forcefield-utilities pull request #28
Opened 2022-09-02 23:33 UTC by CalCraven

Adding in utility functions to switch to loading in GMSO xmls through forcefield-utilities. There are some minor differences in syntax in the the XMLS loaded from the two loaders, so a few changes have to made to make sure the GMSO tests are all sensible when testing the loading using the forcefields in GMSO.

See https://github.com/mosdef-hub/gmso/pull/690 for more info.

2022-09-02 23:34 UTC, CalCraven commented
Need to fix the unit registry here in forcefield-utilities, it's currently just stuck at the top of gmso_xml.py, but probably can get moved to a new module.

2022-09-12 19:24 UTC, daico007 requested changes
Found one spot that need to be double checked, but everything else looks good!

2022-09-12 19:24 UTC, daico007 commented on forcefield_utilities/gmso_xml.py
> +            gmso_pairpotential_type = GMSOBondType(**pairpotential_type_dict)
shouldn't we use GMSOPairPotentialType? (https://github.com/mosdef-hub/gmso/blob/main/gmso/core/pairpotential_type.py)

2022-09-12 21:35 UTC, daico007 approved these changes
LGTM!

2022-09-13 04:55 UTC, merged